---
- name: Manage devices
  hosts: all
  gather_facts: false
  connection: local

  vars:
    cli:
      username: admin
      password: cisco
      transport: cli

  tasks:
    - name: enable ospf
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0

      register: print_output

    -  debug: var=print_output

- name: Switch specific config
  hosts: S5, S6
  gather_facts: false
  connection: local

  vars:
    cli:
      username: admin
      password: cisco
      transport: cli

  tasks:
    - name: Create VLANs
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        lines:
          - vlan 200
          - vlan 300
          - vlan 400
          - vlan 500

      register: print_output

    -  debug: var=print_output
